sudo: false
git:
  depth: 1
language: ruby
rvm:
- &release_ruby 2.4.0
- 2.3.3
- 2.2.6
- 2.1.10
- 2.0.0
- 1.9.3
- 1.8.7
- jruby-9.0.5.0
- jruby-9.1.6.0
- jruby-19mode # based on jruby-1.7.19
- jruby-18mode # based on jruby-1.7.19
#- rbx-3 # NOTE not currently recognized
env:
  global:
  # use system libraries to speed up installation of nokogiri
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script: bundle exec rake coverage test:all
after_success: bundle exec rake build:dependents
notifications:
  email: false
  #irc: 'irc.freenode.org#asciidoctor'
deploy:
  provider: rubygems
  gem: asciidoctor
  on:
    tags: true
    repo: asciidoctor/asciidoctor
    rvm: *release_ruby
  api_key:
    secure: cTp75pHp1WNKstJ/Cw9hC7yCuZ94GA46GVTY/MmqBoisibDEWn8a1mt2nbiDetmwe5OVFU+KC5cWwfaAHcMOo3VyCf63/lHl5hWKk5fhVPxaclwhd8okmWzEmfWjf6wc1lSGsxxVuFMNPiwjBn7Rpka2SA5KZj0mJ3eUkILQESg=
